//*************************************************************
//************************************************************* 

#ifndef _sciInterface_H
#define _sciInterface_H 

//======================================
	void initNoticeSwVersionToUart();

#if defined (UART_DEBUGGING_PROCESSING)
	void aIfSci_DebuggingUART();
#endif //!UART_DEBUGGING_PROCESSING

//======================================
// (7) Initial Process
//======================================
 
#endif // !_sciInterface_H

//*************************************************************
//       Timing processing GUIDELINE
//*************************************************************
#ifndef _sciInterface_H_isr
#define _sciInterface_H_isr
#endif //!_sciInterface_H_isr


#ifndef _sciInterface_H_sysClk
#define _sciInterface_H_sysClk
#endif //!_sciInterface_H_sysClk

